# Generated by Django 3.0.3 on 2020-07-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPersonalWebsiteApp', '0002_auto_20200713_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='contributor',
        ),
        migrations.AddField(
            model_name='post',
            name='contributor_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
