# Generated by Django 3.0.3 on 2020-07-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPersonalWebsiteApp', '0004_auto_20200714_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
